theme: jekyll-theme-tactile
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: false
titles_from_headings:
  enabled:     true
  strip_title: true
  collections: true 
index_page: home.md
